services:
  - type: web
    name: merng
    runtime: node
    plan: free
    buildCommand: npm install --production=false && npm run build
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        scope: run
      - key: JWT_SECRET
        scope: run
      - key: NODE_ENV
        value: production
